
CXX		= g++
LD              = g++
LDFLAGS         += -Wl,-rpath,$(LEAFDIR)/lib
FFLAGS          += -Wall
FLDFLAGS        += -lstdc++ -shared 
CXXFLAGS        += -g -O2 -Wall -fPIC
SOMAKER         = g++
SOFLAGS         = -g -shared 
