
CXX		= g++
LD              = g++
LDFLAGS         += -Wl,-rpath,$(RASPBERRY_ANALYSIS)/lib
FFLAGS          += -Wall
FLDFLAGS        += -lstdc++ -shared 
CXXFLAGS        += -g -O2 -W -Wall -Wno-deprecated -fPIC
SOMAKER         = g++
SOFLAGS         = -g -shared 
