export LEAFDIR=../
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$LEAFDIR/lib
export ROOT_INCLUDE_PATH=${LEAFDIR}/LEAF/DataModel-lite

export WCSIMDIR=${LEAFDIR}/libWCSIM
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$WCSIMDIR